singularity {
    enabled = true
    autoMounts = true
}

process {
    executor = 'slurm'
    queue = 'main'
    memory = '8G'
    cpus = 4
    time = '1h'
}

executor {
    name = 'slurm'
    queueSize = 100
    submitRateLimit = '50/1min'
}
