singularity {
    enabled = true
    autoMounts = true
}

process {
    executor = 'slurm'
    queue = 'main'
    memory = '32G'
    cpus = 16
    time = '24h'
}

executor {
    name = 'slurm'
    queueSize = 100
    submitRateLimit = '50/1min'
}
